### ISSUE TITLE
Fatal error occured when initializing

### ISSUE THREAD

**Issue by timint** [LilacMeteorObservatory/MetDetPy#4]
Hi. Looks like a lot of work was made to this. 👍Thanks for 
I had some trouble running this on Windows.

I did this:
```
pipenv shell
pip install -r requirements.txt
python MetDetPy.py "./test/20220413Red.mp4" --mask "./test/mask-east.jpg"
```

And got this:
```
Info: Parsing "exp_option"=auto
Info: Metainfo FPS = 25.00
Info: ThreadVideoLoader summary:
    Video path: "./test/20220413Red.mp4"; Mask path: "./test/mask-east.jpg";
    Video frames = 317; Apply grayscale = True;
    Raw resolution = [3840, 2160]; Running-time resolution = [960, 540];
Apply exposure time of 0.16s.(MinTimeFlag = 960)
Total frames = 317 ; FPS = 25.00 (rFPS = 6.25)
Info: Preprocessing finished. Time cost: 7.8s.
Info: Parsing "exp_option"=0.16
Info: Metainfo FPS = 25.00
Error: Fatal error occured when initializing. MetDetPy will exit.
Traceback (most recent call last):
  File "~\MetDetPy\MetDetPy.py", line 325, in <module>
    result = detect_video(args.target,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\MetDetPy\MetDetPy.py", line 132, in detect_video
    raise e
  File "~\MetDetPy\MetDetPy.py", line 107, in detect_video
    meteor_collector = MeteorCollector(
                       ^^^^^^^^^^^^^^^^
  File "~\MetDetPy\MetLib\MeteorLib.py", line 91, in __init__
    self.met_exporter = MetExporter(runtime_size=runtime_size,
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\MetDetPy\MetLib\MeteorLib.py", line 539, in __init__
    self.recheck_model = init_model(recheck_cfg.model)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\MetDetPy\MetLib\Model.py", line 201, in init_model
    return Model(**cfg, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "~\MetDetPy\MetLib\Model.py", line 51, in __init__
    self.backend: Backend = self.BackendCls(self.weight_path,
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~\MetDetPy\MetLib\Model.py", line 152, in __init__
    self.model_session = ort.InferenceSession(self.weight_path,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxxx\.virtualenvs\MetDetPy-rlpov0Y-\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 419, in __init__
    self._create_inference_session(providers, provider_options, disabled_optimizers)
  File "C:\Users\xxxx\.virtualenvs\MetDetPy-rlpov0Y-\Lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 480, in _create_inference_session
    sess = C.InferenceSession(session_options, self._model_path, True, self._read_config_from_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
onnxruntime.capi.onnxruntime_pybind11_state.InvalidProtobuf: [ONNXRuntimeError] : 7 : INVALID_PROTOBUF : Load model from ./weights/yolov5s.onnx failed:Protobuf parsing failed.

```

**Comment by Designerspr** [comment]
Hi, and thank you for your appreciation! There are several possible reasons that may cause the InvalidProtobuf error. Please check the following steps:

1. Firstly, the weight file (./weights/yolov5s.onnx) should be a binary file with a size of about 27MB. It is managed by git-lfs, so when you download it from GitHub (instead of cloning it), the weight file will be only a text file. If this is the case, you should download it individually from [this link](https://github.com/LilacMeteorObservatory/MetDetPy/raw/refs/heads/main/weights/yolov5s.onnx?download=) and replace the text file.

2. If the file is downloaded but the error still occurs, please check if the weight file is not corrupted. Its hash code should be `sha256:15518222579e3e4de52b6a709a6bcd8b3f53773737a9edc1ef2e79aff9e415e7`. If it is corrupted, please redownload it and try again.

3. Update runtime library for onnxruntime. Install the latest necessary runtime [MSVC library](https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170).

4. Try an older onnxruntime version (e.g., onnxruntime==1.16.0). Newer onnxruntime libraries may cause the InvalidProtobuf error (though this has not been validated yet).

If the above methods do not solve your problem, please provide more information about your environment, including your onnxruntime version, pip package list, and hardware environment.

**Comment by timint** [comment]
Thank you for getting back to me.

```
[packages]
numpy = ">=1.15.0"
opencv-python = ">=4.9.0"
tqdm = ">=4.0.0"
easydict = ">=1.0"
multiprocess = ">=0.70.0"
onnxruntime = ">=1.16.0"
```

The contents of ./weights/yolov5s.onnx is indeed 1 kb as following:
```
version https://git-lfs.github.com/spec/v1
oid sha256:15518222579e3e4de52b6a709a6bcd8b3f53773737a9edc1ef2e79aff9e415e7
size 28631459
```
With the binary file in place it's rolling! 👍
![image](https://github.com/user-attachments/assets/f84cd6e2-9248-4934-9024-513d63f5de0b)

**Comment by timint** [comment]
I can confirm a successful match with one of my own meteor captures. And a successful "no match" for a non-meteor.
It's just awesome when the first test runs turns come out nicely. Can't wait to play with it some more. :)
